### PR TITLE
Fix the link to examples.

### PR DESCRIPTION
**Pull request by smirnoffs**
The link was pointing to non-existing branch `feature-openapi`.

### CODE REVIEW

**Comment by playpauseandstop** [comment]
Thanks for fixing this. I will merge this early tomorrow. 

One side note, Circle CI checks failed due to update setup.py hook, as after changing README, it is needed to update auto generated  setup.p file with `make setup.py`

**Comment by smirnoffs** [comment]
I guess this check could be ignored for `README.md`. 

Thank you for the interesting project BTW. It's very inspiring. I always liked "contract first" approach.

**Comment by playpauseandstop** [comment]
That is good point, I’ll investigate whether it is possible to entire drop setup.py from the project. It is used for Read the Docs needs only, btw

**Comment by playpauseandstop** [comment]
Yes, it is possible to not use `setup.py` for generating documentation via Read the Docs. Removing entire pre-commit-hook to update `setup.py` as it not needed anymore...

**Comment by playpauseandstop** [comment]
Merged! 

Thanks for fix and the cause to remove `setup.py` from the project :)

**Pull request merged**
