### PR TITLE
Use typing_extensions only for python<3.8

### PR DESCRIPTION
**Pull request by q0w**

### CODE REVIEW

**Comment by playpauseandstop** [comment]
@q0w 

Hi there!

While I understand the reasoning behind this PR, I believe it will not fix the original problem for you and `typing-extensions` will still be installed, while you're using `rororo`, as `aiohttp` **always** require it via: https://github.com/aio-libs/aiohttp/blob/68bbe75e36d691e10ced11239543ad528cf7122b/setup.cfg#L55

So, at one side I'm open to merge this to `master`, but from other hand `typing-extensions` still will be installed, but now via `aiohttp` dependency list.

Please let me know on your thoughts after ^

**Comment by q0w** [comment]
@playpauseandstop 
They did it for python3.8+
https://github.com/aio-libs/aiohttp/pull/5374
https://github.com/aio-libs/aiohttp/pull/5912

**Comment by playpauseandstop** [comment]
@q0w 

Gosh. You're completely correct. `master` branch of `aiohttp` do not means latest code, and they for sure install `typing-extenisions` only for Python 3.8- in `3.8.1` version: https://github.com/aio-libs/aiohttp/blob/cc6dc0c49f5d002485f9a3cdf9bc3127a3ac1388/setup.cfg#L58

Starting process of merging this into `rororo@master`.

Thanks for the PR!

**Review by playpauseandstop — APPROVED** [review]

**Comment by q0w** [comment]
Should it be through try/except ImportError or by checking python version?

**Comment by playpauseandstop** [comment]
> Should it be through try/except ImportError or by checking python version?

I am fine with proposed solution, to try to import from `typing` and then fallback to `typing_extensions`.

CI is fine with that solutions as well...

**Pull request merged**
